version: '3.3'

services:
  app:
    container_name: "pgi_app"
    build:
      context: ./docker
      dockerfile: Dockerfile-app
    ports:
      - 8888:80
    restart: always
    depends_on:
      - db
    volumes:
      - "./source:/var/www"
      - "./storage/app:/var/www/storage/app"
      - "./storage/logs:/var/www/storage/logs"

  db:
    container_name: "pgi_db"
    build:
      context: ./docker
      dockerfile: Dockerfile-db
    ports:
      - 3306:3306
    restart: always
    volumes:
      - "./storage/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: "pgi_api"
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
