FROM php:7.3-apache-stretch

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get autoremove

RUN apt-get install -y \
    apt-utils \
    git \
    zip \
    zlib1g-dev \
    libzip-dev \
    libbz2-dev \
    libpng-dev \
    libicu-dev \
    g++

RUN docker-php-ext-install \
    zip \
    bz2 \
    mbstring \
    bcmath \
    pdo_mysql \
    gd

ENV TZ="America/Sao_Paulo"
RUN date

RUN docker-php-ext-configure intl && \
    docker-php-ext-install intl

RUN a2enmod rewrite

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

RUN sed -ri -e 's!/var/www/html!/var/www/public!g' /etc/apache2/sites-available/*.conf

WORKDIR /var/www/

CMD apachectl -D FOREGROUND
