@extends('layouts.external')

@section('content')
<p class="lead text-white">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel aliquet diam. Integer volutpat urna vel nulla mollis, luctus imperdiet odio semper. Aenean non diam sed dui auctor consectetur vitae id est. Mauris non arcu ac turpis ullamcorper ultricies ut vitae tortor. Maecenas eu neque et mauris ultricies elementum. Suspendisse eget sapien feugiat, laoreet sem nec, luctus est. Vestibulum auctor lectus quis erat rutrum, quis sodales eros vulputate. Nunc in lectus nulla. Praesent quis porttitor nisl, vel accumsan nibh. Nunc quis odio vestibulum, hendrerit erat quis, dignissim odio. Sed volutpat euismod orci.</p>

<p class="lead text-white">Vivamus semper suscipit dui nec malesuada. Etiam ullamcorper id purus nec fermentum. Nulla vel suscipit tortor, in tincidunt mi. Aliquam eu molestie erat, nec pharetra nisl. Quisque nec massa sed metus luctus ultricies. Vestibulum blandit nisl vitae cursus semper. In id diam in nulla consequat maximus id eu augue. Nunc semper felis in ultricies maximus. Nulla a scelerisque ipsum, non mollis erat.</p>

<p class="lead text-white">Sed bibendum nunc et lectus tristique bibendum. Curabitur sit amet ullamcorper est. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam et massa mollis, varius nisi at, ultricies turpis. Ut vehicula scelerisque enim non pharetra. Quisque risus diam, tristique ut commodo malesuada, congue quis turpis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent hendrerit felis quis elit placerat pulvinar. Nunc ornare dignissim scelerisque. Aliquam tortor dui, tempor nec viverra vel, faucibus a enim. Nullam et nisi nisl. Suspendisse vulputate orci posuere arcu condimentum, eget mollis justo semper. Nullam lorem diam, consectetur sed dapibus euismod, auctor vel ipsum. Aenean consectetur dictum sem vitae luctus.</p>

<p class="lead text-white">Sed finibus id quam eget elementum. Donec convallis purus sapien, in gravida mauris suscipit ut. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In venenatis feugiat erat non dictum. Vivamus iaculis pharetra magna a dignissim. Proin est nisi, ullamcorper id massa sed, rhoncus ullamcorper leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
@endsection
